stages:
  - build

build:
  stage: build
  before_script:
    - echo "Vérification de Python et pip"
    - python3 --version || sudo apt-get update && sudo apt-get install -y python3
    - pip3 --version || sudo apt-get install -y python3-pip
  script:
    - pip3 install -r requirements.txt -t ./dependencies
    - zip -r dependencies.zip ./dependencies
  artifacts:
    paths:
      - dependencies.zip
