stages:
  - build

build:
  stage: build
  tags:
    - docker
  image: python:3.12  # Utilisation de l'image officielle Python

  script:
    - pip install -r requirements.txt -t ./dependencies  # Installation des dépendances
    - zip -r dependencies.zip ./dependencies             # Création du fichier ZIP
  artifacts:
    paths:
      - dependencies.zip
