stages:
  - build

build:
  stage: build
  tags:
    - docker
  image: python:3.12  # Image officielle avec Python 3.12 et pip préinstallés
  before_script:
    - echo "Vérification de Python et pip"
    - python --version  # Vérifie la version de Python
    - pip --version     # Vérifie que pip est disponible
  script:
    - pip install -r requirements.txt -t ./dependencies  # Installation des dépendances
    - zip -r dependencies.zip ./dependencies             # Création du ZIP
  artifacts:
    paths:
      - dependencies.zip
