stages:
  - build

build:
  stage: build
  script:
    - pip install -r requirements.txt -t ./dependencies
    - zip -r dependencies.zip ./dependencies
  artifacts:
    paths:
      - dependencies.zip
