stages:
  - build
  - download_windows_dependencies

build:
  stage: build
  tags:
    - docker
  image: python:3.12  # Utilisation de l'image officielle Python
  before_script:
    - apt-get update && apt-get install -y zip python3 pip # Installation de zip
    - pip install --upgrade pip
    # - pip install setuptools
    - python3 -m pip install --user pipx
    - python3 -m pip install --user --upgrade pipx
    - python3 -m pipx ensurepath --global # optional to allow pipx actions with --global argument
    - source ~/.bashrc
    - pipx install poetry  # Installation de poetry
    - pipx inject poetry poetry-plugin-export

  script:
    - poetry lock 
    - poetry install --only main # Installation des dépendances avec poetry
    - poetry export -f requirements.txt --output requirements-poetry.txt --without-hashes  # Export des dépendances vers requirements.txt
    - pip install -r requirements-poetry.txt --target ./dependencies-logbase --upgrade
    # - pip install -r requirements-poetry.txt --prefix vendor --upgrade
    - zip -r dependencies-logbase.zip dependencies-logbase  # Création du fichier ZIP
  artifacts:
    paths:
      - dependencies-logbase.zip
  only:
    - main

download_windows_dependencies:
  stage: download_windows_dependencies
  tags:
    - docker
  image: python:3.12  # Utilisation de l'image officielle Python
  before_script:
    - apt-get update && apt-get install -y zip python3 pip # Installation de zip
    - pip install --upgrade pip
    # - pip install setuptools
    - python3 -m pip install --user pipx
    - python3 -m pip install --user --upgrade pipx
    - python3 -m pipx ensurepath --global # optional to allow pipx actions with --global argument
    - source ~/.bashrc
    - pipx install poetry  # Installation de poetry
    - pipx inject poetry poetry-plugin-export

  script:
    - poetry lock
    - poetry install --only main # Installation des dépendances avec poetry
    - poetry export -f requirements.txt --output requirements-poetry.txt --without-hashes  # Export des dépendances vers requirements.txt
    - pip download --platform win_amd64 --no-deps --dest dependencies-logbase -r requirements-poetry.txt  # Téléchargement des dépendances Windows
    - zip -r dependencies-logbase-windows.zip dependencies-logbase  # Création du fichier ZIP pour Windows
  artifacts:
    paths:
      - dependencies-logbase-windows.zip
  only:
    - main